spring:
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.orm.jpa: info
    org.springframework.transaction: info
