/*
 * This source file was generated by the Gradle 'init' task
 */
package com.esieeit.projetsi;

public class MessageUtils {
    public static String getMessage() {
        return "hello world";
    }
}
